AWSTemplateFormatVersion: '2010-09-09'
Description: 'Simplified HTTP API Gateway configuration for debugging'

Parameters:
  Environment:
    Type: String
    Description: Deployment environment
  
  ProjectName:
    Type: String
    Description: Project name for resource naming
  
  LambdaFunctionArn:
    Type: String
    Description: ARN of the Basic Auth Lambda function
  
  OAuth2FunctionArn:
    Type: String
    Description: ARN of the OAuth2 Lambda function
  
  ThrottleRateLimit:
    Type: Number
    Default: 100
    Description: API Gateway throttle rate limit (requests per second)
  
  ThrottleBurstLimit:
    Type: Number
    Default: 500
    Description: API Gateway throttle burst limit

Resources:
  # Simple HTTP API Gateway
  HttpApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Sub '${ProjectName}-api-${Environment}'
      Description: !Sub 'Java Authorization Server HTTP API - ${Environment}'
      ProtocolType: HTTP
      CorsConfiguration:
        AllowOrigins:
          - '*'
        AllowMethods:
          - POST
          - GET
          - OPTIONS
        AllowHeaders:
          - Authorization
          - Content-Type
        MaxAge: 300

  # Basic Auth Lambda integration
  AuthLambdaIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref HttpApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Ref LambdaFunctionArn
      PayloadFormatVersion: '2.0'
      TimeoutInMillis: 29000

  # OAuth2 Lambda integration
  OAuth2LambdaIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref HttpApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Ref OAuth2FunctionArn
      PayloadFormatVersion: '2.0'
      TimeoutInMillis: 29000

  # Basic authentication route
  AuthRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: 'POST /auth'
      Target: !Sub 'integrations/${AuthLambdaIntegration}'
      AuthorizationType: NONE

  # Legacy authentication validation route (for backward compatibility)
  AuthValidateRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: 'POST /auth/validate'
      Target: !Sub 'integrations/${AuthLambdaIntegration}'
      AuthorizationType: NONE

  # OAuth2 token endpoint
  OAuth2TokenRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: 'POST /oauth/token'
      Target: !Sub 'integrations/${OAuth2LambdaIntegration}'
      AuthorizationType: NONE

  # OAuth2 token introspection endpoint
  OAuth2IntrospectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: 'POST /oauth/introspect'
      Target: !Sub 'integrations/${OAuth2LambdaIntegration}'
      AuthorizationType: NONE

  # Health check route
  HealthRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: 'GET /health'
      Target: !Sub 'integrations/${AuthLambdaIntegration}'
      AuthorizationType: NONE

  # API Gateway Stage
  ApiStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref HttpApi
      StageName: !Ref Environment
      AutoDeploy: true

  # Lambda permission for Basic Auth function
  AuthLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Select [6, !Split [":", !Ref LambdaFunctionArn]]
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${HttpApi}/*/*'

  # Lambda permission for OAuth2 function
  OAuth2LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Select [6, !Split [":", !Ref OAuth2FunctionArn]]
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${HttpApi}/*/*'

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}'
    Export:
      Name: !Sub '${ProjectName}-${Environment}-ApiEndpoint'
  
  ApiGatewayId:
    Description: API Gateway ID
    Value: !Ref HttpApi
    Export:
      Name: !Sub '${ProjectName}-${Environment}-ApiGatewayId' 