AWSTemplateFormatVersion: '2010-09-09'
Description: 'Simplified Secrets Manager configuration for debugging'

Parameters:
  Environment:
    Type: String
    Description: Deployment environment
  
  ProjectName:
    Type: String
    Description: Project name for resource naming

Resources:
  # Simplified KMS Key
  SecretsKMSKey:
    Type: AWS::KMS::Key
    Properties:
      Description: !Sub 'KMS key for ${ProjectName} secrets - ${Environment}'
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 'kms:*'
            Resource: '*'

  # Secret with proper JSON structure for user credentials - UPDATED WITH MULTIPLE USERS
  CredentialSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${ProjectName}-credentials-${Environment}'
      Description: !Sub 'User credentials for ${ProjectName} - ${Environment}'
      KmsKeyId: !Ref SecretsKMSKey
      SecretString: !Sub |
        {
          "testuser": {
            "passwordHash": "$argon2id$v=19$m=65536,t=3,p=1$tAfnCOGvfoqtpA8fdehxjQ$xeVLzYR+9PcmvjOfYBvblNEIUlVSV4s/PeRKvNU3HGY",
            "status": "ACTIVE",
            "roles": ["user"]
          },
          "alice": {
            "passwordHash": "$argon2id$v=19$m=65536,t=3,p=1$J3my/3MwoX3e4mCNqFcMGA$+Sh2QfahQMZ454+IR+XAuX0U22R6YHRBIKalT8YC3eU",
            "status": "ACTIVE",
            "roles": ["user"]
          },
          "bob": {
            "passwordHash": "$argon2id$v=19$m=65536,t=3,p=1$+qyvmHFOBbQyU62T4bFUGw$p9mZumOahbDWBEiimJJ2bLoYuaTpcWYff+ygw1TqDeY",
            "status": "ACTIVE",
            "roles": ["user"]
          },
          "charlie": {
            "passwordHash": "$argon2id$v=19$m=65536,t=3,p=1$ZbUeZYSintna31p04n/ZXA$NK1CCI3WO35DxxXG3DB8CL4X3ko9SIMLaYxB4XH6ihA",
            "status": "DISABLED",
            "roles": ["user"]
          },
          "admin": {
            "passwordHash": "$argon2id$v=19$m=65536,t=3,p=1$ovzPgleixNHMV+cepIlzWw$NsHuxaEXVh1XsZlPuP2Nnmh2fbUeQlLG6nG4PYmlXFw",
            "status": "ACTIVE",
            "roles": ["admin", "user"]
          },
          "developer": {
            "passwordHash": "$argon2id$v=19$m=65536,t=3,p=1$II/3n5IJxNtlVA+yQ9vEpg$Yb5PO2pvMIBtG1rOgQonq/BVwslgAzL9zr+E0tmtu/4",
            "status": "ACTIVE",
            "roles": ["developer", "user"]
          }
        }

Outputs:
  CredentialSecretArn:
    Description: ARN of the credential secret
    Value: !Ref CredentialSecret
    Export:
      Name: !Sub '${ProjectName}-${Environment}-CredentialSecretArn'
  
  SecretsKMSKeyId:
    Description: KMS Key ID for secrets encryption
    Value: !Ref SecretsKMSKey
    Export:
      Name: !Sub '${ProjectName}-${Environment}-SecretsKMSKeyId' 