AWSTemplateFormatVersion: '2010-09-09'
Description: 'Simplified Secrets Manager configuration for debugging'

Parameters:
  Environment:
    Type: String
    Description: Deployment environment
  
  ProjectName:
    Type: String
    Description: Project name for resource naming

Resources:
  # Simplified KMS Key
  SecretsKMSKey:
    Type: AWS::KMS::Key
    Properties:
      Description: !Sub 'KMS key for ${ProjectName} secrets - ${Environment}'
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 'kms:*'
            Resource: '*'

  # Secret with proper JSON structure for user credentials
  CredentialSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${ProjectName}-credentials-${Environment}'
      Description: !Sub 'User credentials for ${ProjectName} - ${Environment}'
      KmsKeyId: !Ref SecretsKMSKey
      SecretString: !Sub |
        {
          "testuser": {
            "passwordHash": "$argon2id$v=19$m=65536,t=3,p=1$tAfnCOGvfoqtpA8fdehxjQ$xeVLzYR+9PcmvjOfYBvblNEIUlVSV4s/PeRKvNU3HGY",
            "status": "ACTIVE",
            "roles": ["user"]
          }
        }

Outputs:
  CredentialSecretArn:
    Description: ARN of the credential secret
    Value: !Ref CredentialSecret
    Export:
      Name: !Sub '${ProjectName}-${Environment}-CredentialSecretArn'
  
  SecretsKMSKeyId:
    Description: KMS Key ID for secrets encryption
    Value: !Ref SecretsKMSKey
    Export:
      Name: !Sub '${ProjectName}-${Environment}-SecretsKMSKeyId' 